version: "3"
services:
  webapp:
    build: .
    image: {{ name }}-webapp
    ports:
      - "{{port}}:{{port}}"
    volumes:
      - ".:/code"
    command: |
      /bin/bash -c "
        npm install && npm run dev
      "
